### ISSUE TITLE
What is the best way to handle wrong URL?

### ISSUE THREAD

**Issue by marsPure** [espresso3389/HttpStream#2]
What is the best way to handle a situation where there is no file exist on the server and URL is wrong?
I could do it with reading a length in a try catch block and if it didn't throw an exception the URL is valid. 
is this the best way?

**Comment by espresso3389** [comment]
Yes, currently, it's the only way to see the errors.
But I think there should be some way to know the exact cause of the error such as HTTP status code. I need some modification to do that.

**Comment by espresso3389** [comment]
On [2.0.50](https://www.nuget.org/packages/HttpStream/2.0.50), I added [HttpStream.LastHttpStatusCode](https://github.com/espresso3389/HttpStream/blob/master/HttpStream/HttpStream.cs#L149).
It does not change the error checking scheme but it helps you to know more about the error.
