### ISSUE TITLE
Publish a new version on NuGet?

### ISSUE THREAD

**Issue by 0xced** [espresso3389/HttpStream#6]
Hello, two years ago several improvements were merged: #3, #4, #5. But unfortunately, a new version was never published on NuGet The last published version is still [2.0.52.3](https://www.nuget.org/packages/Espresso3389.HttpStream/2.0.52.3) from 20/02/2019.

Do you plan to publish a new version?

I can help setup a GitHub actions workflow if you want to automate publishing on NuGet.

**Comment by espresso3389** [comment]
Wow, your contribution is always welcome. Should I do something or could you give me a PR?

**Comment by espresso3389** [comment]
Sorry for long absense.
64-bit update is already merged. But should I do any other thing before publishing new version?
I didn't catch up the latest .NET discussion recently :(

**Comment by bjornharrtell** [comment]
I think it's fine! No reason to go higher than netstandard2.0 yet/in this case.

**Comment by espresso3389** [comment]
[2.0.68](https://www.nuget.org/packages/Espresso3389.HttpStream/2.0.68) is published!
